from __future__ import annotations

from quotemux.capabilities.inventory import MERGE_STRATEGY_APPEND_DEDUPE, MERGE_STRATEGY_FIELD_CONSENSUS, MERGE_STRATEGY_FIRST_SUCCESS, MERGE_STRATEGY_FRESHEST_WINS, MERGE_STRATEGY_PRIORITY_FALLBACK, RESULT_SHAPE_EVENT_STREAM, RESULT_SHAPE_KEYED_RECORDS, RESULT_SHAPE_RAW_PASSTHROUGH, RESULT_SHAPE_REFERENCE_TABLE, RESULT_SHAPE_SINGLE_RECORD, RESULT_SHAPE_TIME_SERIES


MERGE_STRATEGY_FIRST_SUCCESS = MERGE_STRATEGY_FIRST_SUCCESS
MERGE_STRATEGY_PRIORITY_FALLBACK = MERGE_STRATEGY_PRIORITY_FALLBACK
MERGE_STRATEGY_FRESHEST_WINS = MERGE_STRATEGY_FRESHEST_WINS
MERGE_STRATEGY_FIELD_CONSENSUS = MERGE_STRATEGY_FIELD_CONSENSUS
MERGE_STRATEGY_APPEND_DEDUPE = MERGE_STRATEGY_APPEND_DEDUPE

MERGE_STRATEGY_SOURCE_PRIORITY = MERGE_STRATEGY_PRIORITY_FALLBACK
MERGE_STRATEGY_FASTEST_VALID = MERGE_STRATEGY_FIRST_SUCCESS
MERGE_STRATEGY_BEST_SCORE = MERGE_STRATEGY_FRESHEST_WINS
MERGE_STRATEGY_WEIGHTED_CONSENSUS = MERGE_STRATEGY_FIELD_CONSENSUS
MERGE_STRATEGY_MAJORITY_CONSENSUS = MERGE_STRATEGY_FIELD_CONSENSUS
MERGE_STRATEGY_RAW_PASSTHROUGH = "raw_passthrough"

LEGACY_MERGE_STRATEGY_ALIASES = {
    MERGE_STRATEGY_BEST_SCORE: MERGE_STRATEGY_FRESHEST_WINS,
    MERGE_STRATEGY_FASTEST_VALID: MERGE_STRATEGY_FIRST_SUCCESS,
    MERGE_STRATEGY_MAJORITY_CONSENSUS: MERGE_STRATEGY_FIELD_CONSENSUS,
    MERGE_STRATEGY_SOURCE_PRIORITY: MERGE_STRATEGY_PRIORITY_FALLBACK,
    MERGE_STRATEGY_WEIGHTED_CONSENSUS: MERGE_STRATEGY_FIELD_CONSENSUS,
}

MERGE_STRATEGIES = (
    MERGE_STRATEGY_FIRST_SUCCESS,
    MERGE_STRATEGY_PRIORITY_FALLBACK,
    MERGE_STRATEGY_FRESHEST_WINS,
    MERGE_STRATEGY_FIELD_CONSENSUS,
    MERGE_STRATEGY_APPEND_DEDUPE,
    MERGE_STRATEGY_RAW_PASSTHROUGH,
)

RESULT_SHAPE_STRATEGIES = {
    RESULT_SHAPE_SINGLE_RECORD: (
        MERGE_STRATEGY_PRIORITY_FALLBACK,
        MERGE_STRATEGY_FRESHEST_WINS,
        MERGE_STRATEGY_FIELD_CONSENSUS,
        MERGE_STRATEGY_FIRST_SUCCESS,
        MERGE_STRATEGY_RAW_PASSTHROUGH,
    ),
    RESULT_SHAPE_KEYED_RECORDS: (
        MERGE_STRATEGY_PRIORITY_FALLBACK,
        MERGE_STRATEGY_FIELD_CONSENSUS,
        MERGE_STRATEGY_FRESHEST_WINS,
        MERGE_STRATEGY_RAW_PASSTHROUGH,
    ),
    RESULT_SHAPE_TIME_SERIES: (
        MERGE_STRATEGY_APPEND_DEDUPE,
        MERGE_STRATEGY_FRESHEST_WINS,
        MERGE_STRATEGY_PRIORITY_FALLBACK,
        MERGE_STRATEGY_RAW_PASSTHROUGH,
    ),
    RESULT_SHAPE_REFERENCE_TABLE: (
        MERGE_STRATEGY_PRIORITY_FALLBACK,
        MERGE_STRATEGY_FRESHEST_WINS,
        MERGE_STRATEGY_FIRST_SUCCESS,
        MERGE_STRATEGY_RAW_PASSTHROUGH,
    ),
    RESULT_SHAPE_EVENT_STREAM: (
        MERGE_STRATEGY_APPEND_DEDUPE,
        MERGE_STRATEGY_FRESHEST_WINS,
        MERGE_STRATEGY_PRIORITY_FALLBACK,
        MERGE_STRATEGY_RAW_PASSTHROUGH,
    ),
    RESULT_SHAPE_RAW_PASSTHROUGH: (
        MERGE_STRATEGY_PRIORITY_FALLBACK,
        MERGE_STRATEGY_FRESHEST_WINS,
        MERGE_STRATEGY_RAW_PASSTHROUGH,
    ),
}


def normalize_merge_strategy(strategy: str) -> str:
    return LEGACY_MERGE_STRATEGY_ALIASES.get(strategy, strategy)


def list_merge_strategies() -> tuple[str, ...]:
    return MERGE_STRATEGIES


def allowed_merge_strategies(result_shape: str) -> tuple[str, ...]:
    return RESULT_SHAPE_STRATEGIES.get(result_shape, RESULT_SHAPE_STRATEGIES[RESULT_SHAPE_RAW_PASSTHROUGH])
